use std::env;
use std::fs;
use std::path::Path;

/// Languages embedded in the binary. Everything else is fetched on demand.
const EMBEDDED_LANGUAGES: &[&str] = &[
    // English
    "english", "english_1k", "english_5k", "english_10k", "english_25k",
    "english_commonly_misspelled", "english_contractions", "english_doubleletter",
    // Major European
    "spanish", "spanish_1k", "spanish_10k",
    "french", "french_1k", "french_2k", "french_10k",
    "german", "german_1k", "german_10k",
    "portuguese", "portuguese_1k", "portuguese_3k", "portuguese_5k",
    "italian", "italian_1k", "italian_7k",
    "dutch", "dutch_1k", "dutch_10k",
    "swedish", "swedish_1k",
    "norwegian_bokmal", "norwegian_bokmal_1k",
    "danish", "danish_1k",
    "finnish", "finnish_1k",
    "polish", "polish_2k", "polish_5k", "polish_10k",
    "czech", "czech_1k",
    "hungarian", "hungarian_1k",
    "romanian", "romanian_1k",
    "greek", "greek_1k",
    "turkish", "turkish_1k", "turkish_5k",
    // Cyrillic
    "russian", "russian_1k", "russian_5k", "russian_10k",
    "ukrainian", "ukrainian_1k",
    // Asian
    "japanese_romaji", "japanese_romaji_1k", "japanese_hiragana", "japanese_katakana",
    "korean", "korean_1k", "korean_5k",
    "chinese_simplified", "chinese_simplified_1k", "chinese_simplified_5k",
    "chinese_traditional", "chinese_traditional_1k", "chinese_traditional_5k",
    "hindi", "hindi_1k",
    "indonesian", "indonesian_1k",
    "vietnamese", "vietnamese_1k",
    "thai", "thai_1k", "thai_5k",
    "pinyin", "pinyin_1k",
];

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();

    let lang_dir = Path::new("data/languages");
    let mut all_langs: Vec<String> = Vec::new();

    if let Ok(entries) = fs::read_dir(lang_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.ends_with(".txt") && !name.starts_with('_') {
                all_langs.push(name.trim_end_matches(".txt").to_string());
            }
        }
    }
    all_langs.sort();

    let embedded: Vec<&String> = all_langs
        .iter()
        .filter(|l| EMBEDDED_LANGUAGES.contains(&l.as_str()))
        .collect();
    let remote: Vec<&String> = all_langs
        .iter()
        .filter(|l| !EMBEDDED_LANGUAGES.contains(&l.as_str()))
        .collect();

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n\n");

    for lang in &embedded {
        let const_name = lang.to_uppercase().replace('-', "_").replace(' ', "_");
        code.push_str(&format!(
            "const LANG_{}: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/data/languages/{}.txt\"));\n",
            const_name, lang
        ));
    }

    code.push_str("\npub fn build_language_map() -> HashMap<&'static str, &'static str> {\n");
    code.push_str(&format!(
        "    let mut m = HashMap::with_capacity({});\n",
        embedded.len()
    ));
    for lang in &embedded {
        let const_name = lang.to_uppercase().replace('-', "_").replace(' ', "_");
        code.push_str(&format!("    m.insert(\"{}\", LANG_{});\n", lang, const_name));
    }
    code.push_str("    m\n}\n\n");

    code.push_str("pub const LANGUAGE_NAMES: &[&str] = &[\n");
    for lang in &all_langs {
        code.push_str(&format!("    \"{}\",\n", lang));
    }
    code.push_str("];\n\n");

    code.push_str("pub const REMOTE_LANGUAGE_NAMES: &[&str] = &[\n");
    for lang in &remote {
        code.push_str(&format!("    \"{}\",\n", lang));
    }
    code.push_str("];\n");

    // Code languages
    let code_dir = Path::new("data/code");
    let mut code_langs: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(code_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.ends_with(".txt") {
                code_langs.push(name.trim_end_matches(".txt").to_string());
            }
        }
    }
    code_langs.sort();

    for cl in &code_langs {
        let const_name = cl.to_uppercase().replace('-', "_").replace('+', "PLUS");
        code.push_str(&format!(
            "const CODE_{}: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/data/code/{}.txt\"));\n",
            const_name, cl
        ));
    }

    code.push_str("\npub fn build_code_map() -> HashMap<&'static str, &'static str> {\n");
    code.push_str(&format!(
        "    let mut m = HashMap::with_capacity({});\n",
        code_langs.len()
    ));
    for cl in &code_langs {
        let const_name = cl.to_uppercase().replace('-', "_").replace('+', "PLUS");
        code.push_str(&format!(
            "    m.insert(\"code {}\", CODE_{});\n",
            cl, const_name
        ));
    }
    code.push_str("    m\n}\n\n");

    code.push_str("pub const CODE_LANGUAGE_NAMES: &[&str] = &[\n");
    for cl in &code_langs {
        code.push_str(&format!("    \"code {}\",\n", cl));
    }
    code.push_str("];\n");

    let dest = Path::new(&out_dir).join("languages_generated.rs");
    fs::write(dest, code).unwrap();

    println!("cargo:rerun-if-changed=data/languages");
    println!("cargo:rerun-if-changed=data/code");
}
